name: Administrate
main: net.milkbowl.administrate.Administrate
version: 1.2.2
author: Sleaker
softdepend: [Permissions, PermissionsEx]
commands:
    admin:
        aliases: [at, adminmode]
        description: Toggles administration mode
        usage: /<command>
    stealth:
        description: Toggles a player to appear offline
        usage: /<command>
    vanish:
        aliases: [invis]
        description: turns you invisible and turns on No pickup
        usage: /<command>
    god:
        aliases: [ag, g]
        description: toggles invulnerability
        usage: /<command>
    return:
        description: returns you to your saved location
        usage: /<command>
    saveloc:
        description: saves your current location
        usage: /<command>
    adminstatus:
        aliases: [as]
        description: shows you what options you have active
        usage: /<command>
    fakeout:
        aliases: [fo, fakelogout]
        description: Send a spoofed logout message to all online players.
        usage: /<command>
    fakein:
        aliases: [fi, fakelogin]
        description: Send a spoofed login message to all online players.
        usage: /<command>
    admin_bring:
        aliases: [bring]
        description: bring a player to you.
        usage: /<command> [playername]
    admin_put:
        aliases: [put]
        description: put a player where you are looking.
        usage: /<command> [playername]
    admin_tp:
        aliases: [tp, atp]
        description: basic teleport command.
        usage: /<command> (playername | playername to playername | x y z )
    admin_up:
        aliases: [up]
        description: teleport you up the number of blocks.
        usage: /<command> [int]
    admin_heal:
        aliases: [heal]
        description: heal yourself or a player
        usage: /command [player]