name: Administrate
main: net.milkbowl.administrate.Administrate
version: 1.0.1
author: Sleaker
commands:
    admin:
        aliases: [at, adminmode]
        description: Toggles administration mode
    stealth:
        description: Toggles a player to appear offline
    vanish:
        aliases: [invis]
        description: turns you invisible and turns on No pickup
    god:
        description: toggles invulnerability
    return:
        description: returns you to your saved location
    saveloc:
        description: saves your current location
    adminstatus:
        aliases: [as]
        description: shows you what options you have active